package com.github.g4l9.plugin.cep.client

object Languages {

    val languages: List<Language> = listOf(
        Language("csharp", "C#", listOf("cs"), "dotnet100csharpcoreclr"),
        Language("fsharp", "F#", listOf("fs"), "dotnet100fsharpcoreclr"),
        Language("vb", "Visual Basic", listOf("vb"), "dotnet100vbcoreclr"),
        Language("il", "IL", listOf("il"), "dotnet100ilcoreclr"),
        Language("cuda", "CUDA C++", listOf("cu", "cuh"), "nvcc125u1"),
        Language("c", "C", listOf("c", "h"), "cg161"),
        Language("c++", "C++", listOf("cpp", "cxx", "hpp", "hxx", "cc", "ixx"), "g161"),
        Language("fortran", "Fortran", listOf("f90", "F90", "f95", "F95", "f"), "gfortran161"),
        Language("assembly", "Assembly", listOf("asm", "6502", "s"), "nasm301"),
        Language("hlsl", "HLSL", listOf("hlsl", "hlsli"), "dxc_1_8_2403_2"),
        Language("objc++", "Objective-C++", listOf("mm"), "objcppg161"),
        Language("go", "Go", listOf("go"), "gl1260"),
        Language("objc", "Objective-C", listOf("m"), "objcg161"),
        Language("rust", "Rust", listOf("rs"), "r1970"),
        Language("python", "Python", listOf("py"), "python314"),
        Language("crystal", "Crystal", listOf("cr"), "crystal1203"),
        Language("dart", "Dart", listOf("dart"), "dart373"),
        Language("erlang", "Erlang", listOf("erl", "hrl"), "erl2416"),
        Language("carbon", "Carbon", listOf("carbon"), "carbon-x86-trunk"),
        Language("cobol", "COBOL", listOf("cob", "cbl", "cobol"), "gnucobol32"),
        Language("hook", "Hook", listOf("hk", "hook"), "hook010"),
        Language("hylo", "Hylo", listOf("hylo"), "hylotrunk"),
        Language("julia", "Julia", listOf("jl"), "julia_1_12_5"),
        Language("tablegen", "LLVM TableGen", listOf("td"), "llvmtblgen_trunk"),
        Language("lean", "Lean", listOf("lean"), "lean_4_29_1"),
        Language("lua", "Lua", listOf("lua"), "lua550"),
        Language("mlir", "MLIR", listOf("mlir"), "mliropt1600"),
        Language("mojo", "Mojo", listOf("mojo", "🔥"), "mojo_nightly"),
        Language("nix", "Nix", listOf("nix"), "nix2290"),
        Language("odin", "Odin", listOf("odin"), "odin202607a"),
        Language("ptx", "PTX", listOf("ptx"), "ptxasnvcc_131"),
        Language("perl", "Perl", listOf("pl", "pm"), "perl5422"),
        Language("racket", "Racket", listOf("rkt"), "racketnightly"),
        Language("raku", "Raku", listOf("raku", "rakutest", "rakumod", "rakudoc"), "rakudo-moar-2026-06-01"),
        Language("ruby", "Ruby", listOf("rb"), "ruby405"),
        Language("ada", "Ada", listOf("adb", "ads"), "gnat161"),
        Language("sail", "Sail", listOf("sail"), "sail_0_20_2"),
        Language("typescript", "TypeScript Native", listOf("ts", "d.ts"), "tsc_0_0_20_gc"),
        Language("v", "V", listOf("v", "vsh"), "v04"),
        Language("vala", "Vala", listOf("vala"), "valac05606"),
        Language("wasm", "WASM", listOf("wat"), "wasmtimetrunk"),
        Language("swift", "Swift", listOf("swift"), "swift633"),
        Language("cpp_for_opencl", "C++ for OpenCL", listOf("clcpp", "cl", "ocl"), "armv8-cpp4oclclang-trunk"),
        Language("c3", "C3", listOf("c3"), "c3c0711"),
        Language("llvm", "LLVM IR", listOf("ll"), "llctrunk"),
        Language("clojure", "Clojure", listOf("clj"), "clojure1123"),
        Language("cmakescript", "CMakeScript", listOf("cmake"), "cmake-3_31_5"),
        Language("cpp2_cppfront", "Cpp2-cppfront", listOf("cpp2"), "cppfront_trunk"),
        Language("d", "D", listOf("d"), "ldc1_42"),
        Language("glsl", "GLSL", listOf("glsl"), "glslang-validator-trunk"),
        Language("ispc", "ispc", listOf("ispc"), "ispc1310"),
        Language("java", "Java", listOf("java"), "java2501"),
        Language("kotlin", "Kotlin", listOf("kt"), "kotlinc2220"),
        Language("llvm_mir", "LLVM MIR", listOf("mir"), "mirllctrunk"),
        Language("pascal", "Pascal", listOf("pas", "dpr", "inc"), "fpc322"),
        Language("nim", "Nim", listOf("nim"), "nim2210"),
        Language("pony", "Pony", listOf("pony"), "p0670"),
        Language("razorforge", "RazorForge", listOf("rf"), "razorforge020"),
        Language("solidity", "Solidity", listOf("sol"), "solc0830"),
        Language("yul", "Yul (Solidity IR)", listOf("yul"), "resolc140_yul"),
        Language("scala", "Scala", listOf("scala"), "scalac371"),
        Language("slang", "Slang", listOf("slang"), "slangc_2026_8_1"),
        Language("snowball", "Snowball", listOf("sn"), "snowballv010"),
        Language("spice", "Spice", listOf("spice"), "spice02700"),
        Language("spirv", "SPIR-V", listOf("spvasm"), "spirv-opt-master"),
        Language("sway", "sway", listOf("sw"), "swayv0712"),
        Language("javascript", "Javascript", listOf("mjs"), "v8trunk"),
        Language("vyper", "Vyper", listOf("vy"), "vyper040"),
        Language("clean", "Clean", listOf("icl"), "clean30_64"),
        Language("algol68", "Algol68", listOf("a68"), "ga68-g161"),
        Language("modula2", "Modula-2", listOf("mod"), "gm2161"),
        Language("haskell", "Haskell", listOf("hs", "haskell", "ghc9122"), "gnat161"),
        Language("ocaml", "OCaml", listOf("ml", "mli", "ocaml5200"), "gnat161"),
        Language("ylc", "Ygen", listOf("yl"), "ylc_newest"),
        Language("zig", "Zig", listOf("zig"), "z0160")
    )

    val ext2language: Map<String, Language> =
        languages.flatMap { language -> language.extensions.map { ext -> ext to language } }.toMap()

}
